AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CaBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-ca-backend-api
      Description: Regional API gateway for the verifier certificate authority service
      StageName: !Ref Environment
      OpenApiVersion: 3.0.0
      AccessLogSetting:
        DestinationArn: !GetAtt CaBackendApiAccessLogs.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      EndpointConfiguration:
        Type: REGIONAL
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: false
          MetricsEnabled: true
          ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 10
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openApiSpecs/ca-public-spec.yaml

  CaBackendApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-ca-backend-api-access-logs
      RetentionInDays: 30

  CaBackendApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CaBackendApiDomainName
      RestApiId: !Ref CaBackendApi
      Stage: !Ref CaBackendApi.Stage

  CaBackendApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: "" #!FindInMap
#        - EnvironmentVariables
#        - !Ref Environment
#        - SelfUrl
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Sub '{{resolve:ssm:/${Environment}/Platform/ACM/PrimaryZoneWildcardCertificateARN}}'
      SecurityPolicy: TLS_1_2

  CaBackendApiRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CaBackendApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt CaBackendApiDomainName.RegionalHostedZoneId
      HostedZoneId: !Sub '{{resolve:ssm:/${Environment}/Platform/Route53/PrimaryZoneID}}'
      Name: !Ref CaBackendApiDomainName
      Type: A

  CaBackendApiWebAclAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub
        - "arn:aws:apigateway:${AWS::Region}::/restapis/${CaBackendApi}/stages/${ApiStage}"
        - ApiStage: !Ref CaBackendApi.Stage
      WebACLArn:
        Fn::ImportValue: !Sub "${AWS::StackName}-cf-dist-CloakingOriginWebACLArn"