openapi: 3.0.3
info:
  title: Gov Checker CA Backend – Reader Certificate API
  version: '1.0.0'
  description: |
    Issues short-lived reader certificates (valid for ~24 hours) for Verifier Apps.
    v1 uses the programme-standard app integrity pattern:
    - The app obtains a Firebase App Check token
    - The token is validated by /client-attestation
    - /client-attestation returns a client attestation JWT bound to the app's public key
    - The app sends that JWT to this API along with a CSR

servers:
  - url: https://api.example.com

paths:
  /issue-reader-cert:
    post:
      summary: Issue short-lived reader certificate
      description: |
        Issues a short-lived X.509 reader certificate.
        The CSR’s public key must match the public key bound into the client attestation JWT.
      operationId: issueReaderCert
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueReaderCertRequest'
            examples:
              ios_example:
                value:
                  csrPem: |
                    -----BEGIN CERTIFICATE REQUEST-----
                    MIIC...
                    -----END CERTIFICATE REQUEST-----
                  clientAttestationJwt: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ...'
              android_example:
                value:
                  csrPem: |
                    -----BEGIN CERTIFICATE REQUEST-----
                    MIIC...
                    -----END CERTIFICATE REQUEST-----
                  clientAttestationJwt: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ...'
      responses:
        '200':
          description: Reader certificate issued successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueReaderCertResponse'
        '400':
          description: Invalid request (bad CSR, missing fields, invalid JSON)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Client attestation failed or policy rejected the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                attestation_invalid:
                  summary: Client attestation JWT invalid
                  value:
                    code: 'attestation_invalid'
                    message: 'Client attestation JWT is invalid or expired'
                key_binding_mismatch:
                  summary: CSR public key does not match attestation binding
                  value:
                    code: 'key_binding_mismatch'
                    message: 'CSR public key does not match client attestation binding'
        '429':
          description: Too many requests / rate limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error issuing certificate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    IssueReaderCertRequest:
      type: object
      required:
        - csrPem
        - clientAttestationJwt
      properties:
        csrPem:
          type: string
          description: |
            PKCS#10 Certificate Signing Request in PEM encoding.
            The CSR public key must match the public key bound into the client attestation JWT.
        clientAttestationJwt:
          type: string
          description: |
            Backend-issued client attestation JWT (from `/client-attestation`),
            bound to the Verifier App public key.
    IssueReaderCertResponse:
      type: object
      required:
        - readerId
        - certChain
        - profile
        - notBefore
        - notAfter
      properties:
        readerId:
          type: string
        certChain:
          type: object
          required: [leaf, intermediate]
          properties:
            leaf:
              type: string
              description: Leaf reader certificate (PEM encoded)
            intermediate:
              type: string
              description: Intermediary CA certificate (PEM encoded)
        profile:
          type: string
        notBefore:
          type: string
          format: date-time
        notAfter:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
