openapi: 3.0.3
info:
  title: Nonce Service API
  version: '1.0.0'
  description: |
    Public endpoint that issues cryptographically secure, single-use nonces for replay protection or
    challenge-response workflows

servers:
  - url: https://api.example.com

paths:
  /nonce:
    post:
      summary: Mint a fresh nonce
      description: >
        Creates and returns a cryptographically secure 256-bit nonce, Base64URL-encoded (no padding).
        Each nonce is stored server-side with a 5-minute TTL and may be consumed exactly once by downstream
        endpoints that require it.
      operationId: createNonce
      security: []
      requestBody:
        required: false
        description: Optional, reserved for future fields (e.g., audience/purpose).
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NonceServiceFunction.Arn}:live/invocations'
        passthroughBehavior: when_no_match
      responses:
        '201':
          description: Nonce created.
          headers:
            Location:
              description: Opaque URI for the created nonce resource (not necessarily retrievable).
              schema:
                type: string
                example: '/nonce/_opaque_id_'
            Cache-Control:
              description: 'Response must not be cached by clients or intermediaries.'
              schema:
                type: string
                example: 'no-store'
            Date:
              description: RFC 7231 date of the response.
              schema:
                type: string
            X-Request-Id:
              description: Correlation ID for tracing and debugging.
              schema:
                type: string
                example: 'req_01J9ZQ2M7F5N4WPM1V7F3G1H7N'
            Access-Control-Allow-Origin:
              description: CORS origin permitted (set by gateway or edge).
              schema:
                type: string
                example: '*'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NonceResponse'
              examples:
                example:
                  value:
                    nonce: 'q3i2aI4A2d2qU2C9m1vF1b3JYyG3n0o7cJc9Kc4E8fQ'
                    expiresAt: '2025-10-23T12:34:56Z'
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  schemas:
    NonceString:
      type: string
      description: >
        Base64URL-encoded (RFC 4648 ยง5) representation of a 256-bit (32-byte) nonce.
        Must use the URL-safe alphabet and contain **no padding** (`=` characters).
        For 32 bytes, the encoded length is exactly 43 characters.
      pattern: '^[A-Za-z0-9_-]{43}$'
      example: q3i2aI4A2d2qU2C9m1vF1b3JYyG3n0o7cJc9Kc4E8fQ

    NonceResponse:
      type: object
      required:
        - nonce
        - expiresAt
      properties:
        nonce:
          $ref: '#/components/schemas/NonceString'
        expiresAt:
          type: string
          format: date-time
          description: RFC 3339 UTC timestamp indicating when the nonce will expire (5 minutes after generation).
          example: '2025-10-23T12:34:56Z'

    Problem:
      type: object
      description: RFC 7807 Problem Details object.
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          example: 'https://api.example.com/problems/internal-error'
        title:
          type: string
          example: 'Internal Server Error'
        status:
          type: integer
          example: 500
        detail:
          type: string
          example: 'An unexpected error occurred while generating the nonce.'
        instance:
          type: string
          format: uri
          example: 'https://api.example.com/trace/req_01J9ZQ2M7F5N4WPM1V7F3G1H7N'
        code:
          type: string
          description: Machine-readable error code.
        meta:
          type: object
          additionalProperties: true

security: []

tags:
  - name: Nonces
    description: Public minting of short-lived, single-use nonces.
