AWSTemplateFormatVersion: '2010-09-09'

Resources:
  NonceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: '!Sub ${AWS::StackName}-nonce-store'
      KeySchema:
        - AttributeName: nonceValue
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: nonce
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: timeToLive
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
