AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  NonceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-nonce-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: nonceValue
          AttributeType: S
      KeySchema:
        - AttributeName: nonceValue
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: timeToLive
        Enabled: true

  NonceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/
      Handler: nonce-service/src/handler.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          NONCE_TABLE_NAME: !Ref NonceTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NonceTable
      Events:
        NonceApi:
          Type: Api
          Properties:
            Path: /nonce
            Method: post

Outputs:
  NonceApi:
    Description: "API Gateway endpoint URL for Nonce function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/nonce"